[package]
name = "solutiont5"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.20.2"
regex = "1.11.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"

[[test]]
name = "tests"
path = "src/tests.rs"
